dn_dbt:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: postgres
      dbname: taxi
      schema: public

    prod:
      type: postgres
      threads: 1
      host: "{{ env_var('DN_POSTGRES_HOST') }}"
      port: "{{ env_var('DN_POSTGRES_PORT') | int }}"
      user: "{{ env_var('DN_POSTGRES_USER') }}"
      pass: "{{ env_var('DN_POSTGRES_PASSWORD') }}"
      dbname: taxi
      schema: public

  target: dev
